### ISSUE TITLE
generate vectors problem on slurm!

### ISSUE THREAD

**Issue by jeonghun3572** [starsuzi/PRO-ConvQA#1]
sampling from 11: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████| 22262/22262 [00:08<00:00, 2702.18it/s]
sampling from 12: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████| 186119/186119 [01:10<00:00, 2637.11it/s]

.......................
skip
.......................

 Training chain component 0/1
  Input training set too big (max size is 65536), sampling 65536 / 20327660 vectors
OPQMatrix::train: training an OPQ rotation matrix for M=96 from 65536 vectors in 768D -> 768D
  OPQMatrix::train: making random 768*768 rotation
Training PQ slice 0/96
Clustering 65536 points in 8D to 256 clusters, redo 1 times, 40 iterations
  Preprocessing in 0.00 s
  Iteration 39 (0.46 s, search 0.43 s): objective=5136.56 imbalance=1.027 nsplit=0

.......................
skip
.......................

Training PQ slice 95/96
Clustering 65536 points in 8D to 256 clusters, redo 1 times, 4 iterations
  Using 256 centroids provided as input (not frozen)
  Preprocessing in 0.00 s
  Iteration 3 (0.04 s, search 0.03 s): objective=2294.03 imbalance=1.096 nsplit=0
    encode / decode
    Iteration 9 (4 PQ iterations):80.597 s, obj=3.12186
    X * recons
   Applying transform 0/1
   Training sub-index
**WARNING clustering 20327660 points to 1048576 centroids: please provide at least 40894464 training points**

This message is displayed.

**Comment by jeonghun3572** [comment]
I wrote the title wrong. “bash scripts/run/orquac/4_index.sh” is running, not “generating vectors”.

**Comment by starsuzi** [comment]
You can just ignore the warning message or refer to this link to close the warning:
https://github.com/facebookresearch/faiss/wiki/FAQ#can-i-ignore-warning-clustering-xxx-points-to-yyy-centroids
